shoppingCart/shoppingCart/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shoppingCart.Controllers
{
    public class LoginController : Controller
    {
        /// <summary>
        /// 選擇何種登入方式
        /// Admin or Client
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

shoppingCart/shoppingCart/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shoppingCart.Models.Product;


namespace shoppingCart.Controllers
{
    public class ProductController : Controller
    {
        readonly private ProductService productService = new ProductService();

        /// <summary>
        /// 首頁
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            List<Product> model = productService.GetAllProduct();

            return View("Index", model);
        }

        /// <summary>
        /// 新增頁面
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 新增資料進DB
        /// </summary>
        /// <param name="newProductData">新增的資料</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Product newProductData)
        {
            ViewBag.IsCreateSuccess = false;

            if (ModelState.IsValid)
            {
                productService.AddProduct(newProductData);
                ModelState.Clear();
                ViewBag.IsCreateSuccess = true;
            }

            return View();
        }

        /// <summary>
        /// 刪除DB中的資料
        /// </summary>
        /// <param name="productName">作為刪除依據的商品名稱</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Delete(string productId)
        {
            productService.DeleteProduct(productId);
            return Json(true);
        }

        /// <summary>
        /// 開啟商品更新頁面
        /// </summary>
        /// <param name="productName">作為查詢要更新的商品原始資料的依據</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Update(string productId)
        {
            Product model = productService.GetUpdateProductData(productId);
            return View(model);
        }

        /// <summary>
        /// 更新商品資料
        /// </summary>
        /// <param name="updatedProductData">要更新的資料</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Update(Product updatedProductData)
        {
            ViewBag.IsUpdateSuccess = false;

            if (ModelState.IsValid)
            {
                productService.UpdateProductData(updatedProductData);
                ViewBag.IsUpdateSuccess = true;
            }

            return View(updatedProductData);
        }
    }
}

shoppingCart/shoppingCart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("超簡易商品管理後台", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Product")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>