shoppingCart/shoppingCart/Models/Client/PurchaseHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace shoppingCart.Models.Client
{
    public class PurchaseHistory
    {
        [Display(Name = "使用者Id")]
        public string UserId { get; set; }

        [Display(Name = "商品名稱")]
        public string ProductName { get; set; }

        [Display(Name = "購買數量")]
        public int PurchasedAmount { get; set; }

        [Display(Name = "購買日期")]
        public DateTime PurchaseDate { get; set; }
    }
}

shoppingCart/shoppingCart/Models/Client/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace shoppingCart.Models.Client
{
    public class User
    {
        [Required(ErrorMessage = "請輸入帳號")]
        [RegularExpression("^[A-Za-z0-9]+$", ErrorMessage = "只能輸入英文字母及數字")]
        [Display(Name = "帳號")]
        public string UserId { get; set; }

        [Required(ErrorMessage = "請輸入密碼")]
        [RegularExpression("^[A-Za-z0-9]+$", ErrorMessage = "只能輸入英文字母及數字")]
        [Display(Name = "密碼")]
        public string Password { get; set; }

    }
}

shoppingCart/shoppingCart/Models/Client/UserProductService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.SqlClient;
using System.Data;

namespace shoppingCart.Models.Client
{
    public class UserProductService
    {
        readonly private string connectionStr = new CommonTool().GetConnectionString();

        /// <summary>
        /// 將商品加入購物車
        /// </summary>
        /// <param name="userId">使用者Id</param>
        /// <param name="productId">商品Id</param>
        public void AddProductToShoppingCart(string userId, string productId)
        {
            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"INSERT INTO UserShoppingCart (UserId, ProductId)
                               VALUES (@UserId, @ProductId)";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));
                cmd.Parameters.Add(new SqlParameter("@ProductId", productId));
                cmd.ExecuteNonQuery();

                connection.Close();
            }
        }

        /// <summary>
        /// 確認商品是否存在該使用者的購物車
        /// </summary>
        /// <param name="userId">使用者Id</param>
        /// <param name="productId">商品Id</param>
        /// <returns></returns>
        public bool IsThisProductInThisUserShoppingCart(string userId, string productId)
        {
            DataTable shoppingCartDt = new DataTable();

            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"SELECT *
                               FROM UserShoppingCart
                               WHERE UserId = @UserId AND ProductId = @ProductId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));
                cmd.Parameters.Add(new SqlParameter("@ProductId", productId));

                SqlDataAdapter adapter = new SqlDataAdapter(cmd);
                adapter.Fill(shoppingCartDt);

                connection.Close();
            }

            return shoppingCartDt.Rows.Count != 0;
        }

        /// <summary>
        /// 取得該使用者的購物車內容
        /// </summary>
        /// <param name="userId">使用者Id</param>
        /// <returns></returns>
        public List<Models.Product.Product> GetUserShoppingCart(string userId)
        {
            DataTable shoppingCartDt = new DataTable();

            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"SELECT *
                               FROM UserShoppingCart Cart
                               INNER JOIN Product Pd 
                                ON Cart.ProductId = Pd.ProductId 
                               WHERE UserId = @UserId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));

                SqlDataAdapter adapter = new SqlDataAdapter(cmd);
                adapter.Fill(shoppingCartDt);

                connection.Close();
            }

            return this.MapUserShoppingCart(shoppingCartDt);
        }

        /// <summary>
        /// 把使用者購物車的資料從DataTable中Map進List裡
        /// </summary>
        /// <param name="shoppingCartDt"></param>
        /// <returns></returns>
        private List<Models.Product.Product> MapUserShoppingCart(DataTable shoppingCartDt)
        {
            List<Models.Product.Product> shoppingCartList = new List<Product.Product>();

            foreach (DataRow row in shoppingCartDt.Rows)
            {
                shoppingCartList.Add(new Product.Product
                {
                    ProductId = row["ProductId"].ToString(),
                    ProductName = row["ProductName"].ToString(),
                    ProductPrice = (int)row["ProductPrice"]
                });
            }

            return shoppingCartList;
        }

        /// <summary>
        /// 將商品移出購物車
        /// </summary>
        /// <param name="userId">使用者Id</param>
        /// <param name="productId">產品Id</param>
        public void RemoveFromShoppingCart(string userId, string productId)
        {
            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"DELETE FROM UserShoppingCart
                               WHERE UserId = @UserId AND ProductId = @ProductId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));
                cmd.Parameters.Add(new SqlParameter("@ProductId", productId));

                cmd.ExecuteNonQuery();

                connection.Close();
            }
        }

        /// <summary>
        /// 取得要購買的商品資訊
        /// </summary>
        /// <param name="productId">商品Id</param>
        /// <returns></returns>
        public UserPurchase GetPurchasedProductData(string productId)
        {
            DataTable purchasedProductDt = new DataTable();

            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"SELECT *
                               FROM Product
                               WHERE ProductId = @ProductId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@ProductId", productId));

                SqlDataAdapter adapter = new SqlDataAdapter(cmd);
                adapter.Fill(purchasedProductDt);

                connection.Close();
            }

            return this.MapPurchasedProductData(purchasedProductDt);
        }

        /// <summary>
        /// 把被購買的商品資料的資料從DataTable中Map進List裡
        /// </summary>
        /// <param name="purchasedProductDt"></param>
        /// <returns></returns>
        private UserPurchase MapPurchasedProductData(DataTable purchasedProductDt)
        {
            UserPurchase purchasedProductData = new UserPurchase();
            foreach (DataRow row in purchasedProductDt.Rows)
            {
                purchasedProductData.ProductId = row["ProductId"].ToString();
                purchasedProductData.ProductName = row["ProductName"].ToString();
                purchasedProductData.ProductPrice = (int)row["ProductPrice"];
                purchasedProductData.ProductInStock = (int)row["ProductInStock"];
            }

            return purchasedProductData;
        }

        /// <summary>
        /// 購買
        /// </summary>
        /// <param name="purchasedData">被購買的商品資料</param>
        public void Purchase(UserPurchase purchasedData)
        {
            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"UPDATE Product
                               SET
                                    ProductInStock = @ProductInStock - @PurchasedAmount
                               WHERE ProductId = @ProductId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@ProductInStock", purchasedData.ProductInStock));
                cmd.Parameters.Add(new SqlParameter("@PurchasedAmount", purchasedData.PurchasedAmount));
                cmd.Parameters.Add(new SqlParameter("@ProductId", purchasedData.ProductId));

                cmd.ExecuteNonQuery();

                connection.Close();
            }
        }

        /// <summary>
        /// 新增購買歷史
        /// </summary>
        /// <param name="purchasedData">購買商品資訊</param>
        /// <param name="userId">使用者Id</param>
        public void AddPurchaseHistory(UserPurchase purchasedData, string userId)
        {
            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"INSERT INTO PurchaseHistory (UserId, ProductId, PurchasedAmount, PurchaseDate)
                               VALUES (@UserId, @ProductId, @PurchasedAmount, @PurchaseDate)";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));
                cmd.Parameters.Add(new SqlParameter("@ProductId", purchasedData.ProductId));
                cmd.Parameters.Add(new SqlParameter("@PurchasedAmount", purchasedData.PurchasedAmount));
                cmd.Parameters.Add(new SqlParameter("@PurchaseDate", DateTime.Now));

                cmd.ExecuteNonQuery();

                connection.Close();
            }
        }

        /// <summary>
        /// 取得使用者之購買歷史
        /// </summary>
        /// <param name="userId">使用者Id</param>
        /// <returns></returns>
        public List<PurchaseHistory> GetUserPurchaseHistory(string userId)
        {
            DataTable PurchaseHistoryDt = new DataTable();

            using (SqlConnection connection = new SqlConnection(connectionStr))
            {
                connection.Open();

                string sql = @"SELECT ph.UserId UserId, ph.PurchasedAmount PurchasedAmount, ph.PurchaseDate PurchaseDate, pd.ProductName ProductName
                               FROM PurchaseHistory ph
                               INNER JOIN Product pd
                                   ON ph.ProductId = pd.ProductId
                               WHERE ph.UserId = @UserId";

                SqlCommand cmd = new SqlCommand(sql, connection);
                cmd.Parameters.Add(new SqlParameter("@UserId", userId));

                SqlDataAdapter adapter = new SqlDataAdapter(cmd);
                adapter.Fill(PurchaseHistoryDt);

                connection.Close();
            }

shoppingCart/shoppingCart/Models/Client/UserPurchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace shoppingCart.Models.Client
{
    public class UserPurchase : Models.Product.Product
    {
        /// <summary>
        /// 購買數量
        /// </summary>
        [Display(Name = "購買數量")]
        public int PurchasedAmount { get; set; }
    }
}

shoppingCart/shoppingCart/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shoppingCart.Models.Client;
using shoppingCart.Models.Product;
using shoppingCart.Models.Filter;

namespace shoppingCart.Controllers
{
    public class ClientController : Controller
    {
        readonly private UserService userService = new UserService();
        readonly private ProductService productService = new ProductService();
        readonly private UserProductService userProductService = new UserProductService();

        /// <summary>
        /// 登入畫面
        /// </summary>
        /// <returns></returns>
        public ActionResult LoginPage()
        {
            // 如果Session中有UserId就把頁面導向產品清單畫面
            if(Session["UserId"] != null)
            {
                return RedirectToAction("ProductList");
            }

            return View();
        }

        /// <summary>
        /// 登入
        /// </summary>
        /// <param name="userData">使用者輸入的帳號密碼</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult LoginPage(User userData)
        {
            // 如果DB中有成對的帳號密碼則在Session中加入UserId並導向產品清單畫面
            if(ModelState.IsValid && userService.IsAccountExist(userService.GetAllUser(), userData))
            {
                Session["UserId"] = userData.UserId;
                return RedirectToAction("ProductList");
            }

            ModelState.AddModelError("Password", "輸入有誤，請重新確認帳號密碼");
            ModelState.Remove("Password");
            return View(userData);
        }

        /// <summary>
        /// 註冊畫面
        /// </summary>
        /// <returns></returns>
        public ActionResult Register()
        {
            return View();
        }

        /// <summary>
        /// 註冊
        /// </summary>
        /// <param name="userData">使用者輸入的帳號密碼</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Register(User userData)
        {
            ViewBag.IsCreateSuccess = false;

            if (ModelState.IsValid)
            {
                userService.AddUser(userData);
                ModelState.Clear();
                ViewBag.IsCreateSuccess = true;
            }

            return View();
        }

        /// <summary>
        /// 商品清單畫面(登入成功後)
        /// </summary>
        /// <returns></returns>
        [CustomAuthorize]
        public ActionResult ProductList()
        {
            List<Product> productList = this.productService.GetAllProduct();
            return View(productList);
        }

        /// <summary>
        /// 新增商品至購物車
        /// </summary>
        /// <param name="productId">產品Id</param>
        /// <returns></returns>
        [HttpPost]
        [CustomAuthorize]
        public ActionResult AddProductToShoppingCart(string productId)
        {
            string userId = Session["UserId"].ToString();

            // 若商品尚未加入購物車才可以加進去
            if (!userProductService.IsThisProductInThisUserShoppingCart(userId, productId))
            {
                userProductService.AddProductToShoppingCart(userId, productId);
                return Json(new { IsAddToShoppingCartSuccess = true });

            }

            return Json(new { IsAddToShoppingCartSuccess = false, ThisProductExistInShoppingCart = true });
        }

        /// <summary>
        /// 登出
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [CustomAuthorize]
        public ActionResult Logout()
        {
            Session.Remove("UserId");
            return RedirectToAction("LoginPage");
        }

        /// <summary>
        /// 使用者的購物車
        /// </summary>
        /// <returns></returns>
        [CustomAuthorize]
        public ActionResult ShoppingCart()
        {
            string userId = Session["UserId"].ToString();
            List<Product> shoppingCartList = userProductService.GetUserShoppingCart(userId);

            return View(shoppingCartList);
        }

        /// <summary>
        /// 將商品移出購物車
        /// </summary>
        /// <param name="productId">商品Id</param>
        /// <returns></returns>
        [HttpPost]
        [CustomAuthorize]
        public JsonResult RemoveFromShoppingCart(string productId)
        {
            string userId = Session["UserId"].ToString();
            userProductService.RemoveFromShoppingCart(userId, productId);

            return Json(new { IsRemoveSuccess = true });
        }

        /// <summary>
        /// 商品購買畫面
        /// </summary>
        /// <param name="productId">商品Id</param>
        /// <returns></returns>
        [CustomAuthorize]
        public ActionResult Purchase(string productId)
        {
            UserPurchase purchasedProductData = userProductService.GetPurchasedProductData(productId);
            return View(purchasedProductData);
        }

        /// <summary>
        /// 購買
        /// </summary>
        /// <param name="purchasedData">購買之產品資訊</param>
        /// <returns></returns>
        [HttpPost]
        [CustomAuthorize]
        public ActionResult Purchase(UserPurchase purchasedData)
        {
            string userId = Session["UserId"].ToString();
            userProductService.Purchase(purchasedData);
            userProductService.AddPurchaseHistory(purchasedData, userId);

            ViewBag.IsPurchaseSuccess = true;

            return RedirectToAction("ProductList");
        }

        /// <summary>
        /// 購買歷史畫面
        /// </summary>
        /// <returns></returns>
        [CustomAuthorize]
        public ActionResult PurchaseHistory()
        {
            string userId = Session["UserId"].ToString();
            List<PurchaseHistory> purchasHistoryList = userProductService.GetUserPurchaseHistory(userId);
            return View(purchasHistoryList);
        }
    }
}

shoppingCart/shoppingCart/Views/Client/LoginPage.cshtml
@model shoppingCart.Models.Client.User

<h2>登入畫面</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="登入" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("註冊", "Register")
</div>

shoppingCart/shoppingCart/Views/Client/ProductList.cshtml
@model IEnumerable<shoppingCart.Models.Product.Product>

@{
    var userId = Session["UserId"].ToString();
}

<h2>歡迎 @userId</h2>

@Html.ActionLink("查看購物車", "ShoppingCart", new { }, new { @class = "btn btn-default" })
@Html.ActionLink("查看購買歷史", "PurchaseHistory", new { }, new { @class = "btn btn-default" })


@using (Html.BeginForm("Logout", "Client", FormMethod.Post, new { id = "LogoutForm" }))
{
    <input type="submit" value="登出" class="btn btn-default" id="Logout" />
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductInStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductInStock)
            </td>
            <td>
                <button class="btn btn-default AddProductToCart" id="@item.ProductId">加入購物車</button>
                @Html.ActionLink("購買", "Purchase", new { productId = item.ProductId }, htmlAttributes: new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

shoppingCart/shoppingCart/Views/Client/Purchase.cshtml
@model shoppingCart.Models.Client.UserPurchase

<h2>商品購買</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPrice, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ProductPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="display: none">
            @Html.LabelFor(model => model.ProductInStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductInStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductInStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchasedAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchasedAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchasedAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="購買" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到首頁", "ProductList")
</div>

shoppingCart/shoppingCart/Views/Client/PurchaseHistory.cshtml
@model IEnumerable<shoppingCart.Models.Client.PurchaseHistory>

@{
    ViewBag.Title = "PurchaseHistory";
}

<h2>PurchaseHistory</h2>

<p>
    @Html.ActionLink("回首頁", "ProductList")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchasedAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PurchasedAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PurchaseDate)
        </td>
    </tr>
}

</table>

shoppingCart/shoppingCart/Views/Client/Register.cshtml
@model shoppingCart.Models.Client.User

@{
    if (ViewBag.IsCreateSuccess != null && ViewBag.IsCreateSuccess)
    {
        <script type="text/javascript">
            alert("註冊成功");
        </script>
    }
    else if (ViewBag.IsCreateSuccess != null)
    {
        <script type="text/javascript">
            alert("註冊失敗");
        </script>
    }
}

<h2>註冊</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="註冊" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到登入畫面", "LoginPage")
</div>

shoppingCart/shoppingCart/Views/Client/ShoppingCart.cshtml
@model IEnumerable<shoppingCart.Models.Product.Product>

@{
    ViewBag.Title = "ShoppingCart";
}

<h2>ShoppingCart</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductPrice)
        </td>
        <td>
            @Html.ActionLink("購買", "Purchase", new { productId = item.ProductId }, htmlAttributes: new { @class = "btn btn-default" })
            <button class="RemoveFromShoppingCart btn btn-default" id="@item.ProductId">移出購物車</button>
        </td>
    </tr>
}

</table>

@Html.ActionLink("回首頁", "ProductList")